CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY (
    ID NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(255) NOT NULL,  /*댓글/대댓글 내용*/
    GROUP_ID NUMBER NULL,  /*최상위 댓글은 NULL, 대댓글은 상위 댓글의 ID*/
    REPLY_DEPTH NUMBER NOT NULL,  /*깊이 수준: 0은 댓글, 1 이상은 대댓글*/
    CREATED_DATE DATE DEFAULT SYSDATE,  /*작성일자*/
    UPDATED_DATE DATE,   /*수정일자*/
    STATUS NUMBER DEFAULT 1,  /*댓글 상태 (1: 활성, 0: 삭제)*/
    MEMBER_ID NUMBER NOT NULL,  /*작성자 ID*/
    CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY (MEMBER_ID)
    REFERENCES TBL_MEMBER(ID) ON DELETE CASCADE
);

SELECT * FROM TBL_REPLY;